### ISSUE TITLE
Yabaictl - display order

### ISSUE THREAD

**Issue by Just-Insane** [aiguofer/dotfiles#1]
https://github.com/aiguofer/dotfiles/blob/8bb6e945c673b21508ac7706a3a8145c2cd16441/user/.local/bin/yabaictl#L7

Regarding this line (and https://github.com/koekeishiya/yabai/issues/365#issuecomment-592191658), are these displays left to right ordered in some other manner?

**Comment by aiguofer** [comment]
Indeed in my case they are ordered from left to right. That being said, the ordering in the script applies to where each space will fall. For example, in a 3 monitor set up:
Space 1: monitor 1
Space 2: monitor 2
Space 3: monitor 3
Space 4: monitor 1
Space 5: monitor 2
Space 6: monitor 3

The main reason I did this is because in my linux machine running i3 I have a keybinding to swap spaces 1<->4, 2<->5, 3<->6, so I can essentially "swap contexts" while keeping the same ordering of monitors... I haven't taken the time to do something like that in Yabai, but my brain now makes the connection between keybinding and expected monitor.

**Comment by Just-Insane** [comment]
Ah okay I see. I think I may have to modify that script for my needs (I want specific spaces to always be on specific monitors), but that’s a great starting point, thanks!

**Comment by aiguofer** [comment]
absolutely, glad it was useful to someone else :)

I'll probably be adding some more functionality soon like maintaining previous state and trying to recover whenever I have to restart yabai or run `update-spaces` for whatever reason.

**Comment by aiguofer** [comment]
Btw, just saw your comment in https://github.com/koekeishiya/yabai/issues/541#issuecomment-637839501

I'm essentially using labels to re-map the space indexes. Since MacOS seems to place spaces wherever it wants, and space indexes seem to change, this was the only way I found to have a "consistent" configurable index. In my script, all spaces get labed as: s1, s2, s3... so when I mentioned "Space 1" in my response above, I meant "Space label s1".

**Comment by aiguofer** [comment]
@Just-Insane also... looks like some interesting stuff in the works: https://github.com/koekeishiya/yabai/pull/554
and
https://github.com/koekeishiya/yabai/issues/550

They'll definitely make my script a lot cleaner, but may also help you accomplish what you're after. I doubt `yabai` will ever be as good as i3 since they have to hack on top of MacOS instead of building from scratch... but it certainly keeps getting better and better :)

**Comment by Just-Insane** [comment]
Those do look pretty interesting, I’ll be keeping an eye on those, thanks!
